input AuthorInput {
  firstName: String
  lastName: String
  email: String
  username: String
}

type AuthorEntity {
  authorId: ID!

  firstName: String!
  lastName: String!
  email: String!
  username: String!

  posts: [PostEntity]
}

type PostEntity {
  postId: ID!

  title: String!
  content: String!
  publishedOn: String!

  author: AuthorEntity!
}

type Query {
    authorById(authorId: ID!): AuthorEntity
    allAuthors: [AuthorEntity]!
    authors(authorInput: AuthorInput!): [AuthorEntity]!
}
