input AuthorInput {
  firstName: String
  lastName: String
  email: String
  username: String
}

type AuthorEntity {
  authorId: ID!

  firstName: String!
  lastName: String!
  email: String!
  username: String!

  books: [BookEntity]
}

type BookEntity {
  bookId: ID!

  title: String!
  content: String!
  publishedOn: String!

  author: AuthorEntity!
  comments: [CommentEntity]
}

type CommentEntity {
  commentId: ID!

  name: String!
  content: String!
  publishedOn: String!
  updatedOn: String

  book: BookEntity!
}

type Query {
    authorById(authorId: ID!): AuthorEntity
    allAuthors: [AuthorEntity]!
    authors(authorInput: AuthorInput!): [AuthorEntity]!

    bookById(bookId: ID!): BookEntity
}
